# Generated by Django 3.2 on 2024-06-15 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
